# Generated by Django 4.0.6 on 2022-07-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Category Details Name')),
            ],
            options={
                'verbose_name': 'categorydetail',
                'verbose_name_plural': 'categorydetails',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detailcat', to='main.category_details'),
        ),
    ]
